# Data
ingestion_data_dir: ["data", "02_processed"]
ingestion_metadata_dir: ["data", "02_processed", "metadata"]
job_titles: ["Data Engineer", "Data Scientist", "Data Analyst", "Machine Learning Engineer"]

# Embeddings
embedding_model_name: "sentence-transformers/all-mpnet-base-v2"
embedding_dir: ["data", "03_indexed"]

# app
app_config:
    host: "0.0.0.0"
    port: 7860
app_backend:
    min_resume_size: 1000
app_frontend:
    title: "ResumeWorth"
    description: |
        Discover Your Market Value!

        Unlock the true value of your experience with ResumeWorth. 

        Simply enter your job title, upload your resume, and let our advanced AI analyze your professional background. 
        
        In moments, you'll receive an estimated salary, tailored to your unique skills and experience.
    # Empower your job search with insights that put you a step ahead.
    jobs: ["Data Engineer", "Data Scientist", "Data Analyst", "Machine Learning Engineer"]
    messages:
        job_title_not_found: "You must choose one of the roles in the Job Title section!"
        salary_not_found: |
            There is no good match between resume and available job vacancies.
            We recommend that you submit an extended version of your resume.