# Data
ingestion_data_dir: ["data", "02_processed"]
ingestion_metadata_dir: ["data", "02_processed", "metadata"]
job_titles: ["Data Engineer", "Data Scientist", "Data Analyst", "Machine Learning Engineer"]


# Embeddings
embedding_model:
    model_name: "nomic-ai/nomic-embed-text-v1.5"
    model_kwargs:
        device: "cpu" 
        trust_remote_code: True
    encode_kwargs:
        normalize_embeddings: True
embedding_dir: ["data", "03_indexed"]


# LLM / Text Generation
# See instructions for parameters: https://www.ibm.com/docs/en/watsonx-as-a-service?topic=lab-model-parameters-prompting
generative_model:
    model_name: "M4-ai/tau-1.8B"
    model_kwargs:
        trust_remote_code: True
    generate_kwargs: 
        top_k: 30 
        top_p: 0.7
        temperature: 0.3
        max_new_tokens: 256
# See instructions for the prompt: https://huggingface.co/spaces/Locutusque/Locutusque-Models/blob/main/app.py
prompt_dir: ["data", "04_prompts"]
promp_file: "prompt_template_for_explaning_why_is_a_good_fit.json"


# app
app_config:
    host: "0.0.0.0"
    port: 7860
app_backend:
    min_resume_size: 1000
app_frontend:
    title: "ResumeWorth"
    # Good description example: https://huggingface.co/spaces/sam-hq-team/sam-hq/blob/main/app.py
    description: |
        ### **Discover Your True Market Value and Optimize Your Earnings Potential!**

        In today's competitive job market, understanding your worth is paramount. 
        ResumeWorth empowers you to unlock the true value of your professional experience and skills, ensuring you aim for the salary you truly deserve and write a resume that is a good fit for this. 
        With an intricate blend of cutting-edge Artificial Intelligence system, comprehensive market analysis, and our resume-job match explanation feature, ResumeWorth stands as your personal salary advocate and resume improvement assistant.

        #### How It Works:

        1. **Input Simplicity**:  Start by entering your job title and uploading your resume via our easy-to-use interface.
        2. **Advanced AI Analysis**: Our AI leverages a Large Language Model (LLM) to analyze your professional background by analyzing your experience, skills, and accomplishments.
        3. **Semantic and Keyword-Based Searches**:  Our AI uses both keyword and semantic searches to find job vacancies that match your skills and career context perfectly.
        4. **Tailored Salary Range Estimation**: Receive a personalized salary estimate that reflects your unique skills and the job market, based on the best-matching job vacancies.
        5. **Direct Opportunity Linkage**: Get direct links to job vacancies that align well with your resume, providing immediate career opportunities.
        6. **Resume-Job Match Explanation**: Understand how your resume aligns with the recommended job vacancy through the explanation provided by our Retrieval-Augmented Generation (RAG).
    sources: ["All", "Jobstreet"]
    jobs: ["Data Engineer", "Data Scientist", "Data Analyst", "Machine Learning Engineer"]
    messages:
        job_title_not_found: "WARNING: You must choose one of the roles in the Job Title section!"
        resume_file_not_found: "WARNING: You must upload a file with your resume!"
        too_short_resume: |
            WARNING: Resume too short!
            We recommend that you submit an extended version of your resume.
        salary_not_found: |
            Unfortunately, we are currently unable to infer a salary range for your resume.
        active_job_not_found: |
            Unfortunately, at the moment, we couldn't find active jobs that matches your resume.
    examples:
        1: 
            "source": "All"
            "job_title": "Data Scientist"
            "resume_path": ["data", "01_raw", "resume_examples", "Luis_Rodrigues_Resume_20240421.pdf"]
            "explanation_flag": False
